driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/ganeti']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-11.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - apt::default
      - omnibus::default
      - haskell-platform::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/ganeti
        install_dir: /opt/ganeti
      haskell-platform:
        repo_source: justhub
