#!/bin/bash
#
# Perform necessary ganeti setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Shutting down ganeti"

/usr/sbin/service ganeti stop || error_exit "failed to stop ganeti"

exit 0
